### ISSUE TITLE
启动服务之后会直接闪退

### ISSUE THREAD

**Issue by MatchaCake** [Kr328/ClashForAndroid#157]
```02-26 02:21:44.017 22700     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
02-26 02:21:44.017 22700     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76c66333ac]
02-26 02:21:44.017 22700     0 E Go      :
02-26 02:21:44.017 22700     0 E Go      : goroutine 2738 [running]:
02-26 02:21:44.017 22700     0 E Go      : github.com/Dreamacro/clash/proxy/tun.(*fakeConn).WriteBack(0x4001762e40, 0x400134b000, 0xca, 0x5000, 0x76c68dee40, 0x0, 0x0, 0x0, 0x0)
02-26 02:21:44.017 22700     0 E Go      :      src/github.com/Dreamacro/clash/proxy/tun/utils.go:37 +0x17c
02-26 02:21:44.017 22700     0 E Go      : github.com/Dreamacro/clash/tunnel.handleUDPToLocal(0x76c68e3000, 0x4001762e40, 0x7716c49268, 0x40018a8f40, 0x40008332c0, 0x14)
02-26 02:21:44.017 22700     0 E Go      :      src/github.com/Dreamacro/clash/tunnel/connection.go:104 +0x214
02-26 02:21:44.017 22700     0 E Go      : created by github.com/Dreamacro/clash/tunnel.handleUDPConn.func1
02-26 02:21:44.017 22700     0 E Go      :      src/github.com/Dreamacro/clash/tunnel/tunnel.go:234 +0x3c4
02-26 02:21:44.849 22566 22566 E AndroidRuntime: FATAL EXCEPTION: main
02-26 02:21:44.849 22566 22566 E AndroidRuntime: Process: com.github.kr328.clash, PID: 22566
02-26 02:21:44.849 22566 22566 E AndroidRuntime: android.os.DeadObjectException
02-26 02:21:44.849 22566 22566 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
02-26 02:21:44.849 22566 22566 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:550)
02-26 02:21:44.849 22566 22566 E AndroidRuntime:        at com.github.kr328.clash.service.IClashManager$Stub$Proxy.queryBandwidth(IClashManager.java:4)
02-26 02:21:44.849 22566 22566 E AndroidRuntime:        at com.github.kr328.clash.remote.ClashClient$queryBandwidth$2.invokeSuspend(ClashClient.kt:5)
02-26 02:21:44.849 22566 22566 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
02-26 02:21:44.849 22566 22566 E AndroidRuntime:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
02-26 02:21:44.849 22566 22566 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
02-26 02:21:44.849 22566 22566 E AndroidRuntime:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)
02-26 02:21:44.878   938   938 I /vendor/bin/hw/vendor.qti.hardware.servicetracker@1.0-service: destroyService is called for service : com.github.kr328.clash/.service.ClashManagerService

求dalao有空帮忙看看，多谢orz

**Comment by Kr328** [comment]
FIXED in 1.2.0
