### ISSUE TITLE
[BUG] MIUI13.0.7 点击连接按钮没有反应

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [Kr328/ClashForAndroid#1622]
### 描述此错误

小米12S Ultra，点连接无反应

### 如何复现该错误

步骤 1: 导入服务器列表
步骤 2: 点击连接按钮

### 设备信息

- 机型: 小米12S Ultra
- 系统类型:MIUI 13.0.7
- Android 版本:12

### 应用信息

- 版本:0.10.4-beta
- 安装包文件名:io.github.trojan_gfw.igniter-v0.10.4-beta-230001004-arm64-v8a-release.apk
- 应用来源:github

### 配置文件

```yml
{
    "configs": [
        {
            "method": "",
            "obfs": "",
            "obfsParam": "",
            "password": "***",
            "plugin": "",
            "pluginParam": "",
            "protocol": "",
            "protocolParam": "",
            "remarks": "香港-HK1-1,流量倍率:0.50",
            "reuse_session": false,
            "server": "***",
            "server_port": 443,
            "session_ticket": false,
            "sni": "",
            "tcp_fast_open": false,
            "trojanGoSettings": {
                "mux": {
                    "enable": false,
                    "mux_concurrency": 8,
                    "mux_idle_timeout": 60
                },
                "shadowsocks": {
                    "enable": false,
                    "method": "aes-128-gcm",
                    "password": ""
                },
                "transport_plugin": {
                    "arg": [
                    ],
                    "command": "",
                    "enable": false,
                    "env": [
                    ],
                    "option": "",
                    "type": "plaintext"
                },
                "websocket": {
                    "enable": false,
                    "hostname": "",
                    "path": ""
                }
            },
            "type": "trojan",
            "uuid": "",
            "verify_certificate": true,
            "vmessSettings": {
                "http": {
                    "host": [
                    ],
                    "path": ""
                },
                "kcp": {
                    "congestion": false,
                    "downlinkCapacity": 20,
                    "header": {
                        "type": ""
                    },
                    "mtu": 1460,
                    "readBufferSize": 1,
                    "seed": "",
                    "tti": 20,
                    "uplinkCapacity": 5,
                    "writeBufferSize": 1
                },
                "mux": {
                    "enable": false,
                    "mux_concurrency": 8
                },
                "network": "tcp",
                "quic": {
                    "header": {
                        "type": ""
                    },
                    "key": "",
                    "security": ""
                },
                "tcp": {
                    "header": {
                        "request": "{\n    \"version\": \"1.1\",\n    \"method\": \"GET\",\n    \"path\": [],\n    \"headers\": {}\n}",
                        "response": "{\n    \"version\": \"1.1\",\n    \"status\": \"200\",\n    \"reason\": \"OK\",\n    \"headers\": {}\n}",
                        "type": "none"
                    }
                },
                "tls": {
                    "allowInsecure": false,
                    "allowInsecureCiphers": false,
                    "enable": false
                },
                "ws": {
                    "header": {
                    },
                    "path": ""
                }
            }
        },
```

### 日志

```raw
==============过滤 igniter消息===================
2022-08-16 12:10:20.893 2435-4234/? D/MIUIInput: [MotionEvent] publisher action=0x0, 18590338, channel 'c78aa82 io.github.trojan_gfw.igniter/io.github.trojan_gfw.igniter.MainActivity (server)'
2022-08-16 12:10:20.956 2435-4234/? D/MIUIInput: [MotionEvent] publisher action=0x1, 18590402, channel 'c78aa82 io.github.trojan_gfw.igniter/io.github.trojan_gfw.igniter.MainActivity (server)'
2022-08-16 12:10:20.969 13539-13539/? V/TrojanConfig: {"local_addr":"127.0.0.1","local_port":1081,"remote_server_remark":"日本-TY1-1,流量倍率:1.00","remote_addr":"*****","remote_port":443,"password":["*****"],"log_level":2,"ssl":{"verify":false,"cert":"\/data\/user\/0\/io.github.trojan_gfw.igniter\/cache\/cacert.pem","cipher":"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA","cipher_tls13":"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384","alpn":["h2","http\/1.1"],"sni":""},"enable_ipv6":false}
    
    --------- beginning of system
2022-08-16 12:10:20.991 2435-2589/? I/ActivityManager: Start proc 22030:io.github.trojan_gfw.igniter:proxy/u0a270 for service {io.github.trojan_gfw.igniter/io.github.trojan_gfw.igniter.ProxyService} caller=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.004 22030-22030/? E/w.igniter:prox: Not starting debugger since process cannot load the jdwp agent.
2022-08-16 12:10:21.011 2435-5874/? I/SmartPower.io.github.trojan_gfw.igniter:proxy/10270(22030): died->invisible(43326ms) R(process start ) adj=-10000.
2022-08-16 12:10:21.017 7740-636/? W/MQSService: CallerName:io.github.trojan_gfw.igniter,calling Uid:10270
2022-08-16 12:10:21.018 7740-636/? D/MQSService: registerApplicationScoutThread pid = 22030, packageName = io.github.trojan_gfw.igniter
2022-08-16 12:10:21.028 22030-22030/? V/GraphicsEnvironment: ANGLE Developer option for 'io.github.trojan_gfw.igniter' set to: 'default'
2022-08-16 12:10:21.028 22030-22030/? V/GraphicsEnvironment: ANGLE GameManagerService for io.github.trojan_gfw.igniter: false
2022-08-16 12:10:21.030 22030-22030/? I/ForceDarkHelperStubImpl: initialize for io.github.trojan_gfw.igniter , ForceDarkOrigin
2022-08-16 12:10:21.038 22030-22030/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 22030
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@2c0095a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService }: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4828)
        at android.app.ActivityThread.access$2100(ActivityThread.java:272)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2167)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.app.ActivityThread.main(ActivityThread.java:8237)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1046)
     Caused by: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(:3)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4810)
        	... 9 more
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17088): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17089): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17090): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17091): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17092): avc: denied { getattr } for path="/data/mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17093): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.043 7740-7926/? D/DigestGenerator: digest=============io.github.trojan_gfw.igniterjava.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyServiceXX with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService }: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version XX and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE XX specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to XX used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:XX)
        at android.app.ActivityThread.access$XX(ActivityThread.java:XX)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:XX)
        at android.os.Handler.dispatchMessage(Handler.java:XX)
        at android.os.Looper.loopOnce(Looper.java:XX)
        at android.os.Looper.loop(Looper.java:XX)
        at android.app.ActivityThread.main(ActivityThread.java:XX)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:XX)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:XX)
     Caused by: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version XX and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE XX specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to XX used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:XX)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:XX)
        at android.app.PendingIntent.getActivity(PendingIntent.java:XX)
        at android.app.PendingIntent.getActivity(PendingIntent.java:XX)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(:)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:XX)
2022-08-16 12:10:21.050 7740-7926/? D/MQSEventManager: send MSG_JUDGE_TRANSMISSION packageName io.github.trojan_gfw.igniter
2022-08-16 12:10:21.050 7740-7926/? W/JavaExceptionHandler: Too noisy! skip duplicate java exception report:io.github.trojan_gfw.igniter:proxy now=1660623021050 mLastReportTime=1660622976850 interval=60000
2022-08-16 12:10:21.050 7740-7926/? W/MQSEventManager: Too noisy! Bail the event:io.github.trojan_gfw.igniter:proxy type:1
2022-08-16 12:10:21.053 2435-5874/? I/SmartPower.io.github.trojan_gfw.igniter:proxy/10270(22030): invisible->died(41ms) R(process died ) adj=200.
2022-08-16 12:10:21.054 2435-5874/? I/ActivityManager: Process io.github.trojan_gfw.igniter:proxy (pid 22030) has died: prcp FGS 
2022-08-16 12:10:21.057 2435-5874/? I/AutoStartManagerService: MIUILOG- Reject RestartService service :ComponentInfo{io.github.trojan_gfw.igniter/io.github.trojan_gfw.igniter.ProxyService} uid : 10270
2022-08-16 12:10:21.057 2435-5874/? W/ActivityManager: Bringing down service while still waiting for start foreground: ServiceRecord{3ef6f7 u0 io.github.trojan_gfw.igniter/.ProxyService}

==============过滤 trojan 消息===================
2022-08-16 12:10:20.893 2435-4234/? D/MIUIInput: [MotionEvent] publisher action=0x0, 18590338, channel 'c78aa82 io.github.trojan_gfw.igniter/io.github.trojan_gfw.igniter.MainActivity (server)'
2022-08-16 12:10:20.956 2435-4234/? D/MIUIInput: [MotionEvent] publisher action=0x1, 18590402, channel 'c78aa82 io.github.trojan_gfw.igniter/io.github.trojan_gfw.igniter.MainActivity (server)'
2022-08-16 12:10:20.969 13539-13539/? V/TrojanConfig: {"local_addr":"127.0.0.1","local_port":1081,"remote_server_remark":"日本-TY1-1,流量倍率:1.00","remote_addr":"****","remote_port":443,"password":["****"],"log_level":2,"ssl":{"verify":false,"cert":"\/data\/user\/0\/io.github.trojan_gfw.igniter\/cache\/cacert.pem","cipher":"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA:DES-CBC3-SHA","cipher_tls13":"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384","alpn":["h2","http\/1.1"],"sni":""},"enable_ipv6":false}
    
    --------- beginning of system
2022-08-16 12:10:20.991 2435-2589/? I/ActivityManager: Start proc 22030:io.github.trojan_gfw.igniter:proxy/u0a270 for service {io.github.trojan_gfw.igniter/io.github.trojan_gfw.igniter.ProxyService} caller=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.011 2435-5874/? I/SmartPower.io.github.trojan_gfw.igniter:proxy/10270(22030): died->invisible(43326ms) R(process start ) adj=-10000.
2022-08-16 12:10:21.017 7740-636/? W/MQSService: CallerName:io.github.trojan_gfw.igniter,calling Uid:10270
2022-08-16 12:10:21.018 7740-636/? D/MQSService: registerApplicationScoutThread pid = 22030, packageName = io.github.trojan_gfw.igniter
2022-08-16 12:10:21.028 22030-22030/? V/GraphicsEnvironment: ANGLE Developer option for 'io.github.trojan_gfw.igniter' set to: 'default'
2022-08-16 12:10:21.028 22030-22030/? V/GraphicsEnvironment: ANGLE GameManagerService for io.github.trojan_gfw.igniter: false
2022-08-16 12:10:21.030 22030-22030/? I/ForceDarkHelperStubImpl: initialize for io.github.trojan_gfw.igniter , ForceDarkOrigin
2022-08-16 12:10:21.038 22030-22030/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 22030
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@2c0095a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService }: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4828)
        at android.app.ActivityThread.access$2100(ActivityThread.java:272)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2167)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.app.ActivityThread.main(ActivityThread.java:8237)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1046)
     Caused by: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(:3)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4810)
        	... 9 more
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17088): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17089): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17090): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17091): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17092): avc: denied { getattr } for path="/data/mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.034 22030-22030/? W/w.igniter:proxy: type=1400 audit(0.0:17093): avc: denied { search } for name="mqsas" dev="dm-25" ino=394 scontext=u:r:untrusted_app:s0:c14,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=io.github.trojan_gfw.igniter
2022-08-16 12:10:21.043 7740-7926/? D/DigestGenerator: digest=============io.github.trojan_gfw.igniterjava.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyServiceXX with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService }: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version XX and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE XX specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to XX used with inline replies or bubbles.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:XX)
        at android.app.ActivityThread.access$XX(ActivityThread.java:XX)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:XX)
        at android.os.Handler.dispatchMessage(Handler.java:XX)
        at android.os.Looper.loopOnce(Looper.java:XX)
        at android.os.Looper.loop(Looper.java:XX)
        at android.app.ActivityThread.main(ActivityThread.java:XX)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:XX)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:XX)
     Caused by: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version XX and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE XX specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to XX used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:XX)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:XX)
        at android.app.PendingIntent.getActivity(PendingIntent.java:XX)
        at android.app.PendingIntent.getActivity(PendingIntent.java:XX)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(:)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:XX)
2022-08-16 12:10:21.050 7740-7926/? D/MQSEventManager: send MSG_JUDGE_TRANSMISSION packageName io.github.trojan_gfw.igniter
2022-08-16 12:10:21.050 7740-7926/? W/JavaExceptionHandler: Too noisy! skip duplicate java exception report:io.github.trojan_gfw.igniter:proxy now=1660623021050 mLastReportTime=1660622976850 interval=60000
2022-08-16 12:10:21.050 7740-7926/? W/MQSEventManager: Too noisy! Bail the event:io.github.trojan_gfw.igniter:proxy type:1
2022-08-16 12:10:21.053 2435-5874/? I/SmartPower.io.github.trojan_gfw.igniter:proxy/10270(22030): invisible->died(41ms) R(process died ) adj=200.
2022-08-16 12:10:21.054 2435-5874/? I/ActivityManager: Process io.github.trojan_gfw.igniter:proxy (pid 22030) has died: prcp FGS 
2022-08-16 12:10:21.057 2435-5874/? I/AutoStartManagerService: MIUILOG- Reject RestartService service :ComponentInfo{io.github.trojan_gfw.igniter/io.github.trojan_gfw.igniter.ProxyService} uid : 10270
2022-08-16 12:10:21.057 2435-5874/? W/ActivityManager: Bringing down service while still waiting for start foreground: ServiceRecord{3ef6f7 u0 io.github.trojan_gfw.igniter/.ProxyService}
```

**Comment by Misaka-Mikoto-Tech** [comment]
提错位置了
