### ISSUE TITLE
[BUG] 配置wireguard节点导致软件闪退

### ISSUE THREAD

**Issue by dante2046** [Kr328/ClashForAndroid#1996]
### 描述此错误

当配置文件存在wireguard 类型节点的时候，代理选项卡会无法加载代理组并且导致软件闪退。

### 如何复现该错误

添加了wireguard 类型的节点

### 设备信息

- 机型: xiaomi 12 lite
- 系统类型: miui
- Android 版本:13

### 应用信息

- 版本: 3.0.3
- 安装包文件名: cfa-3.0.3-premium-arm64-v8a-release.apk
- 应用来源:telegram 频道

### 配置文件

```yml
proxies:
  - { name: WARP PLUS,type: wireguard,server: 162.159.193.5,port: 2408,ip: 172.16.0.2,private-key: *******************************,public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=,dns: [1.1.1.1, 8.8.8.8],udp: true,remote-dns-resolve: true }
proxy-groups:
  - { name: proxy,type: select, proxies: [ WARP PLUS] }
rules：
  - GEOIP,CN,DIRECT
  - GEOIP,LAN,DIRECT
  - MATCH,proxy
```

### 日志

```raw
08-08 09:06:12.720 15176 15226 D Http    : Call[In] method=GET path=/status
08-08 09:06:12.721 15237 15243 D Clash   : CallIn method=GET url=/status perm=App
08-08 09:06:12.721 15237 15243 D Clash   : CallOut method=GET url=/status
08-08 09:06:12.721 15176 15226 D Http    : Call[Out] method=GET path=/status responseCode=200
08-08 09:06:12.789 15176 15176 W MirrorManager: this model don't Support
08-08 09:06:12.870 15237 15244 D Clash   : [DNS] dns response source=223.5.5.5:53 qType=A name=s2.govd.cn. answer=["183.240.221.105"]
08-08 09:06:12.872 15237 15244 D Clash   : [DNS] dns response source=223.5.5.5:53 qType=AAAA name=s2.govd.cn. answer=[]
08-08 09:06:13.124 15237 15250 D Clash   : [DNS] dns response source=223.5.5.5:53 qType=AAAA name=s1.govd.cn. answer=[]
08-08 09:06:13.684 15237 15250 D Clash   : [DNS] dns response source=119.29.29.29:53 qType=AAAA name=e1.govd.cn. answer=[]
08-08 09:06:14.017 15176 15176 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
08-08 09:06:14.017 15176 15176 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
08-08 09:06:14.643 15237 15243 D Clash   : [DNS] dns response source=223.5.5.5:53 qType=AAAA name=s1.govd.cn. answer=[]
08-08 09:06:14.686 15237 15242 D Clash   : [DNS] dns response source=119.29.29.29:53 qType=AAAA name=e3.govd.cn. answer=[]
08-08 09:06:14.688 15237 15250 D Clash   : [DNS] dns response source=119.29.29.29:53 qType=A name=e3.govd.cn. answer=["47.123.0.135"]
08-08 09:06:15.104 15237 15237 D Clash   : [DNS] dns response source=223.5.5.5:53 qType=AAAA name=e2.govd.cn. answer=[]
08-08 09:06:15.104 15237 15244 D Clash   : [DNS] dns response source=223.5.5.5:53 qType=A name=e2.govd.cn. answer=["61.152.183.121"]
08-08 09:06:16.178 15237 15246 D Clash   : [DNS] dns response source=119.29.29.29:53 qType=AAAA name=n1.govd.cn. answer=[]
08-08 09:06:16.179 15237 15237 D Clash   : [DNS] dns response source=223.5.5.5:53 qType=A name=n1.govd.cn. answer=["39.105.103.71"]
08-08 09:06:17.225 15237 15251 D Clash   : [DNS] dns response source=223.5.5.5:53 qType=AAAA name=s1.govd.cn. answer=[]
08-08 09:06:18.005 15176 15304 D ProfileInstaller: Skipping profile installation for com.github.kr328.clash
08-08 09:06:19.840 15176 15234 D WebSocket: closed path=/events
08-08 09:06:19.841 15237 15237 D Clash   : CallOut method=GET url=/events
08-08 09:06:19.842 15176 15176 D Events  : Events finished 
08-08 09:06:19.848 15176 15202 D OpenGLRenderer: endAllActiveAnimators on 0xb400007d6ca9f700 (UnprojectedRipple) with handle 0xb400007d6ca205c0
08-08 09:06:22.025 15205 15276 W Shizuku : Stop remote process failed 
08-08 09:06:22.025 15205 15276 W Shizuku : kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
08-08 09:06:22.025 15205 15276 W Shizuku : 	at kotlinx.coroutines.TimeoutCoroutine.run(SourceFile:29)
08-08 09:06:22.025 15205 15276 W Shizuku : 	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(Unknown Source:2)
08-08 09:06:22.025 15205 15276 W Shizuku : 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:159)
08-08 09:06:22.025 15205 15276 W Shizuku : 	at kotlinx.coroutines.DefaultExecutor.run(SourceFile:62)
08-08 09:06:22.025 15205 15276 W Shizuku : 	at java.lang.Thread.run(Thread.java:1012)
08-08 09:06:23.919 15176 15176 I ForceDarkHelperStubImpl: setViewRootImplForceDark: false for com.github.kr328.clash.MainActivity@e76d351, reason: DarkModeEnabled
08-08 09:06:23.929 15176 15289 D AppScoutStateMachine: 15176-ScoutStateMachinecreated
08-08 09:06:23.932 15176 15176 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10286; state: ENABLED
08-08 09:06:23.937 15176 15176 D Proxy   : Reload groups action=com.github.kr328.clash.app.main.proxy.vm.ReloadAction$All@7dff9b5
08-08 09:06:23.937 15176 15236 D Http    : Call[In] method=GET path=/status
08-08 09:06:23.938 15176 15227 D Http    : Call[In] method=GET path=/general
08-08 09:06:23.939 15237 15251 D Clash   : CallIn method=GET url=/general perm=App
08-08 09:06:23.939 15237 15251 D Clash   : CallOut method=GET url=/general
08-08 09:06:23.940 15237 15251 D Clash   : CallIn method=GET url=/status perm=App
08-08 09:06:23.940 15237 15251 D Clash   : CallOut method=GET url=/status
08-08 09:06:23.941 15176 15234 D Http    : Call[Out] method=GET path=/status responseCode=200
08-08 09:06:23.944 15176 15227 D Http    : Call[Out] method=GET path=/general responseCode=200
08-08 09:06:23.967 15176 15227 D Http    : Call[In] method=GET path=/providers/proxies
08-08 09:06:23.967 15176 15176 D Events  : Restart events receivers 
08-08 09:06:23.967 15176 15227 D WebSocket: open path=/events
08-08 09:06:23.970 15237 15251 D Clash   : CallIn method=GET url=/providers/proxies perm=App
08-08 09:06:23.975 15176 15190 W System  : A resource failed to call AbstractCursor.close. 
08-08 09:06:23.975 15176 15190 W System  : A resource failed to call AbstractCursor.close. 
08-08 09:06:23.975 15176 15190 W System  : A resource failed to call AbstractCursor.close. 
08-08 09:06:23.975 15176 15190 W System  : A resource failed to call CursorWrapperInner.close. 
08-08 09:06:23.975 15176 15190 W System  : A resource failed to call CursorWrapperInner.close. 
08-08 09:06:23.976 15176 15190 W System  : A resource failed to call CursorWrapperInner.close. 
08-08 09:06:23.976 15176 15190 W System  : A resource failed to call AbstractCursor.close. 
08-08 09:06:23.976 15176 15190 W System  : A resource failed to call AbstractCursor.close. 
08-08 09:06:23.976 15176 15190 W System  : A resource failed to call CursorWrapperInner.close. 
08-08 09:06:23.977 15176 15190 W System  : A resource failed to call CursorWrapperInner.close. 
08-08 09:06:23.977 15176 15190 W System  : A resource failed to call AbstractCursor.close. 
08-08 09:06:23.977 15176 15190 W System  : A resource failed to call CursorWrapperInner.close. 
08-08 09:06:23.977 15176 15190 W System  : A resource failed to call AbstractCursor.close. 
08-08 09:06:23.978 15176 15190 W System  : A resource failed to call CursorWrapperInner.close. 
08-08 09:06:23.978 15237 15244 D Clash   : CallIn method=GET url=/events perm=App
08-08 09:06:23.994 15176 15176 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-08 09:06:23.994 15176 15176 I HandWritingStubImpl: refreshLastKeyboardType: 1
08-08 09:06:23.994 15176 15176 I HandWritingStubImpl: getCurrentKeyboardType: 1
08-08 09:06:23.999 15176 15176 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-08 09:06:24.001 15176 15176 I HandWritingStubImpl: isKeyboardTypeChanged: false
08-08 09:06:24.003 15237 15251 D Clash   : CallOut method=GET url=/providers/proxies
08-08 09:06:24.004 15176 15234 D Http    : Call[Out] method=GET path=/providers/proxies responseCode=200
08-08 09:06:24.027 15176 15176 W hub.kr328.clash: type=1400 audit(0.0:18612): avc: denied { search } for name="mqsas" dev="dm-44" ino=376 scontext=u:r:untrusted_app:s0:c30,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.github.kr328.clash
08-08 09:06:24.027 15176 15176 W hub.kr328.clash: type=1400 audit(0.0:18613): avc: denied { search } for name="mqsas" dev="dm-44" ino=376 scontext=u:r:untrusted_app:s0:c30,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.github.kr328.clash
08-08 09:06:24.027 15176 15176 W hub.kr328.clash: type=1400 audit(0.0:18614): avc: denied { search } for name="mqsas" dev="dm-44" ino=376 scontext=u:r:untrusted_app:s0:c30,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.github.kr328.clash
08-08 09:06:24.027 15176 15176 W hub.kr328.clash: type=1400 audit(0.0:18615): avc: denied { search } for name="mqsas" dev="dm-44" ino=376 scontext=u:r:untrusted_app:s0:c30,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.github.kr328.clash
08-08 09:06:24.027 15176 15176 W hub.kr328.clash: type=1400 audit(0.0:18616): avc: denied { getattr } for path="/data/mqsas" dev="dm-44" ino=376 scontext=u:r:untrusted_app:s0:c30,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.github.kr328.clash
08-08 09:06:24.031 15176 15236 D WebSocket: closed path=/events
08-08 09:06:24.032 15176 15176 E AndroidRuntime: FATAL EXCEPTION: main
08-08 09:06:24.032 15176 15176 E AndroidRuntime: Process: com.github.kr328.clash, PID: 15176
08-08 09:06:24.032 15176 15176 E AndroidRuntime: kotlinx.serialization.SerializationException: com.github.kr328.clash.app.api.Proxies.Type does not contain element with name 'Wireguard' at path $.providers['default'].proxies[3].type
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at okio.Utf8.getJsonNameIndexOrThrow(Unknown Source:42)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeEnum(Unknown Source:20)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.internal.EnumSerializer.deserialize(SourceFile:13)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:114)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:37)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at com.github.kr328.clash.app.api.Proxies$Proxy$$serializer.deserialize(SourceFile:90)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:114)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:37)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(SourceFile:8)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(SourceFile:33)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(Unknown Source:0)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:114)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:37)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at com.github.kr328.clash.app.api.Providers$Provider$$serializer.deserialize(SourceFile:45)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:114)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:37)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.internal.MapLikeSerializer.readElement(SourceFile:6)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.internal.MapLikeSerializer.readElement(SourceFile:1)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(SourceFile:33)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(Unknown Source:0)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:114)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(SourceFile:37)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at com.github.kr328.clash.app.api.Providers$Provider$All$$serializer.deserialize(SourceFile:29)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue$1(SourceFile:114)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.serialization.json.Json.decodeFromString(SourceFile:20)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at okio._UtilKt.decode(SourceFile:224)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at com.github.kr328.clash.app.api.ProxyProviders$getAll$$inlined$request$default$1.invokeSuspend(Unknown Source:55)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:6)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(SourceFile:54)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:23)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:31)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(SourceFile:108)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:14)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:94)
08-08 09:06:24.032 15176 15176 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@cb5c5a4, androidx.compose.runtime.BroadcastFrameClock@c754f0d, StandaloneCoroutine{Cancelling}@d16cec2, AndroidUiDispatcher@1c154d3]
08-08 09:06:24.033 15176 15176 W OOMEventManagerFK: Failed to mkdir /data/mqsas/hprof/
08-08 09:06:24.033 15237 15244 D Clash   : CallOut method=GET url=/events
```

**Comment by fsyllkn** [comment]
clash for Windows倒是正常，clash for Android确实闪退

**Comment by zyjia** [comment]
我的android也碰到了，有点坑，里面配置了许多订阅信息，只能等等看了

**Comment by dante2046** [comment]
> 我的android也碰到了，有点坑，里面配置了许多订阅信息，只能等等看了

wireguard 一般都是自己定制的，应该没啥影响才对

**Comment by zyjia** [comment]
> > 我的android也碰到了，有点坑，里面配置了许多订阅信息，只能等等看了
> 
> wireguard 一般都是自己定制的，应该没啥影响才对

影响很大，闪退，卸载的话以前的配置都丢了
