### ISSUE TITLE
[BUG] 1.2.2 MIUI 启动崩溃

### ISSUE THREAD

**Issue by Love4Taylor** [Kr328/ClashForAndroid#265]
**描述出现的错误**
启动即崩溃。

**如何复现该错误**
复现步骤:
1. 启动 App

**预期行为**
正常启动。

**日志**
```
java.lang.IllegalStateException: Module with the Main dispatcher had failed to initialize
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:3)
	at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:1)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:3)
	at androidx.appcompat.app.ResourcesFlusher.startCoroutineCancellable(ResourcesFlusher.java:1)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:14)
	at androidx.appcompat.app.ResourcesFlusher.launch$default(ResourcesFlusher.java:7)
	at com.github.kr328.clash.service.ProfileService.onCreate(ProfileService.kt:2)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3997)
	at android.app.ActivityThread.access$1600(ActivityThread.java:228)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7567)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NoSuchMethodError: No static method $load1()Ljava/util/Iterator; in class L$$ServiceLoaderMethods; or its super classes (declaration of '$$ServiceLoaderMethods' appears in base.apk)
	at kotlinx.coroutines.internal.MainDispatcherLoader.loadMainDispatcher(MainDispatchers.kt:1)
	at kotlinx.coroutines.internal.MainDispatcherLoader.<clinit>(MainDispatchers.kt:5)
	at kotlinx.coroutines.Dispatchers.getMain(Dispatchers.kt:1)
	at androidx.appcompat.app.ResourcesFlusher.MainScope(ResourcesFlusher.java:3)
	at com.github.kr328.clash.service.BaseService.<init>(BaseService.kt:1)
	at com.github.kr328.clash.service.ClashManagerService.<init>(ClashManagerService.kt:1)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:1)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3979)
	... 8 more

```

**设备信息 (请完成一下信息):**
 - 机型: Redmi K20 Pro
 - 系统/ROM: MIUI 11
 - Android 版本 11
 - ROM版本 20.3.27

**应用信息**
 - 版本: 1.2.2
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: GitHub Releases

**附加信息**

**Comment by Kr328** [comment]
FIXED https://github.com/Kr328/ClashForAndroid/releases/tag/v1.2.2
