### ISSUE TITLE
[BUG] 1.12.3应用fc

### ISSUE THREAD

**Issue by Gregoryweix** [Kr328/ClashForAndroid#267]
**描述出现的错误**
无法打开应用，表现为打开应用后闪现主页面后显示fc的dialog
上一版本正常使用，log为系统在fc的dialog提供

**日志**
time: 1586922491492
msg: java.lang.IllegalStateException: Migration didn't properly handle: selected_proxies(com.github.kr328.clash.service.data.SelectedProxyEntity).
 Expected:
TableInfo{name='selected_proxies', columns={proxy=Column{name='proxy', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=2, defaultValue='null'}, profile_id=Column{name='profile_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, selected=Column{name='selected', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[ForeignKey{referenceTable='profiles', onDelete='CASCADE', onUpdate='CASCADE', columnNames=[profile_id], referenceColumnNames=[id]}], indices=[]}
 Found:
TableInfo{name='selected_proxies', columns={proxy=Column{name='proxy', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=2, defaultValue='null'}, profile_id=Column{name='profile_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, selected=Column{name='selected', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[ForeignKey{referenceTable='_profiles', onDelete='CASCADE', onUpdate='CASCADE', columnNames=[profile_id], referenceColumnNames=[id]}], indices=[]}
stacktrace: java.lang.IllegalStateException: Migration didn't properly handle: selected_proxies(com.github.kr328.clash.service.data.SelectedProxyEntity).
 Expected:
TableInfo{name='selected_proxies', columns={proxy=Column{name='proxy', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=2, defaultValue='null'}, profile_id=Column{name='profile_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, selected=Column{name='selected', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[ForeignKey{referenceTable='profiles', onDelete='CASCADE', onUpdate='CASCADE', columnNames=[profile_id], referenceColumnNames=[id]}], indices=[]}
 Found:
TableInfo{name='selected_proxies', columns={proxy=Column{name='proxy', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=2, defaultValue='null'}, profile_id=Column{name='profile_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, selected=Column{name='selected', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[ForeignKey{referenceTable='_profiles', onDelete='CASCADE', onUpdate='CASCADE', columnNames=[profile_id], referenceColumnNames=[id]}], indices=[]}
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:28)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:4)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:417)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:1)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:2)
	at androidx.room.util.DBUtil.query(DBUtil.java:1)
	at com.github.kr328.clash.service.data.ProfileDao_Impl$12.call(ProfileDao_Impl.java:3)
	at androidx.room.CoroutinesRoom$Companion$execute$2.invokeSuspend(CoroutinesRoom.kt:2)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**设备信息 (请完成一下信息):**
 - 机型: Redmi K20Pro
 - 系统/ROM: Evolution X（类原生）
 - Android 版本 10

**应用信息**
 - 版本: 1.12.3
 - 安装包文件名: app-release-arm64-v8a.apk
 - 应用来源: github

**Comment by Kr328** [comment]
升级的上个版本是哪个

**Comment by Gregoryweix** [comment]
> 升级的上个版本是哪个

本来从netstack最后一个版本升级后，fc，随后卸载重新安装也是fc

**Comment by Kr328** [comment]
清除数据即可

**Comment by Kr328** [comment]
FIXED in 1.2.4
