### ISSUE TITLE
[BUG] OutOfMemoryError

### ISSUE THREAD

**Issue by atbest** [Kr328/ClashForAndroid#618]
最近更新最新版以后经常FC，典型的错误是OOM。
```
FATAL EXCEPTION: DefaultDispatcher-worker-15
Process: com.github.kr328.clash:background, PID: 8100
java.lang.OutOfMemoryError: Could not allocate JNI Env
 at java.lang.Thread.nativeCreate(Native Method)
 at java.lang.Thread.start(Thread.java:731)
 at f.a.k0.M(:1)
 at f.a.y0.R(:13)
 at f.a.y0.g(:2)
 at c.d.a.r.m.b.v(:5)
 at c.a.a.a.f1.s.e.b$a.c(:4)
 at i.n.j.a.a.p(:2)
 at f.a.r0.run(:4)
 at f.a.x0.L(:2)
 at f.a.p0.a()
 at f.a.q0.g0(:2)
 at f.a.b.p()
 at i.n.j.a.a.p(:2)
 at f.a.r0.run(:4)
 at f.a.p2.a.k()
 at f.a.p2.a$a.run(:9)
```

```
FATAL EXCEPTION: DefaultDispatcher-worker-28
Process: com.github.kr328.clash:background, PID: 19854
f.a.i0: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.IO, Continuation at com.github.kr328.clash.core.bridge.Bridge$onCall$1.invokeSuspend(Bridge.kt)@eccea58]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
 at f.a.r0.e()
 at f.a.r0.run(:4)
 at f.a.p2.a.k()
 at f.a.p2.a$a.run(:9)
Caused by: java.lang.IllegalStateException: Job f2{Cancelling}@410399 is already complete or completing, but is being completed with u[f.a.n1: f2 is cancelling; job=f2{Cancelling}@410399]
 at f.a.r1.T(:4)
 at f.a.b.p()
 at i.n.j.a.a.p(:2)
 ... 3 more
Caused by: f.a.n1: f2 is cancelling; job=f2{Cancelling}@410399
Caused by: java.lang.OutOfMemoryError: Could not allocate JNI Env
 at java.lang.Thread.nativeCreate(Native Method)
 at java.lang.Thread.start(Thread.java:731)
 at f.a.p2.a.b(:2)
 at f.a.p2.a.m()
 at f.a.p2.a.f(:4)
 at f.a.p2.e.z(:1)
 at f.a.p2.e.p()
 at f.a.p0.a()
 at c.d.a.r.m.b.q0()
 at f.a.b.j0(:6)
 at c.d.a.r.m.b.S(:4)
 at com.github.kr328.clash.core.bridge.ClashCall.onCall(:1)
```

**Comment by Kr328** [comment]
换手机吧
