### ISSUE TITLE
[BUG] Crash on background randomly

### ISSUE THREAD

**Issue by aviraxp** [Kr328/ClashForAndroid#635]
**Describe the bug**
Crashes on background randomly.

**To Reproduce**
Can't reliably reproduce.

**Expected behavior**
No crash.

**Screenshots**

**Device Info (please complete the following information):**

 - Device: Redmi Note 7 Pro
 - ROM: LineageOS
 - ROM Version: 17.1
 - Android Version 10

**Application Info (please complete the following information):**

 - Version: 2.1.6
 - Apk File Name:  app-release-arm64-v8a.apk
 - Distribution Channel: Google Play

**Additional context**

**Configure**
If applicable, paste **removed server info** configure
```yaml
# paste here
```

**Logs**
If applicable, paste logs to help detect problem

```
09-12 09:09:10.622 E/AndroidRuntime(6047): FATAL EXCEPTION: main
09-12 09:09:10.622 E/AndroidRuntime(6047): Process: com.github.kr328.clash, PID: 6047
09-12 09:09:10.622 E/AndroidRuntime(6047): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at android.app.ContextImpl.startActivity(ContextImpl.java:952)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at android.app.ContextImpl.startActivity(ContextImpl.java:928)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at c.a.a.a.c.e0$a.onServiceDisconnected(:8)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1972)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1987)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at android.os.Handler.handleCallback(Handler.java:883)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at android.os.Handler.dispatchMessage(Handler.java:100)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at android.os.Looper.loop(Looper.java:214)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at java.lang.reflect.Method.invoke(Native Method)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
09-12 09:09:10.622 E/AndroidRuntime(6047): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```

**Comment by Kr328** [comment]
try latest version
