### ISSUE TITLE
在MIUI通知栏图标启动崩溃

### ISSUE THREAD

**Issue by EnK1** [Kr328/ClashForAndroid#85]
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e35bd6d u0 com.github.kr328.clash/.service.ClashService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1969)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

**Comment by sensen1** [comment]
我也是小米,用的miui10，通知栏图标，确实遇到过问题，建议这样，你去掉它，然后再重新添加它到常用通知栏，我遇到的问题这样是解决了，你可以试一下。

**Comment by Kr328** [comment]
FIXED in 1.1.0
